### ISSUE TITLE
PHP Fatal error, line 219

### ISSUE THREAD

**Issue by bradspry** [discoverygarden/islandora_xquery#11]
[03-Dec-2014 16:51:17 America/New_York] PHP Fatal error:  Cannot use string offset as an array in /path/sites/all/modules/islandora_xquery/islandora_xquery.module on line 219

SOLR search works successfully without checking "XQuery search and replace" checkbox.

Checking XQuery search and replace checkbox results in WSOD and fatal PHP error message above.

**Comment by jordandukart** [comment]
Post on the Google groups addressing this: https://groups.google.com/forum/#!topic/islandora/8v4ZiUKp2EI

**Comment by bradspry** [comment]
Thank You!!!
![xquery-success](https://cloud.githubusercontent.com/assets/7230377/5292634/aab9bd0e-7b32-11e4-9f49-9858eff47234.jpg)
